# Generated by Django 4.0.3 on 2022-04-04 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogauthor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogauthor',
            old_name='wegsite',
            new_name='website',
        ),
    ]
