# Generated by Django 4.0.3 on 2022-04-05 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogdetailpage_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogdetailpage',
            old_name='blog_image',
            new_name='banner_image',
        ),
    ]
