# Generated by Django 4.0.3 on 2022-04-04 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subcribers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcriber',
            options={'verbose_name': 'Subcriber', 'verbose_name_plural': 'Subcribers'},
        ),
    ]
